sudo: required
addons:
  chrome: stable
language: node_js
node_js:
- node
script:
- npm run test-ci
- npm run build-ci
before_deploy:
- cd dist/ngxobjectmanager
deploy:
  provider: npm
  email: smiles2424@gmail.com
  skip_cleanup: true
  api_key:
    secure: UwYeH+TK/evtWXegKG268NrFZTMLD2Qb7n0OvfrXGFci1HcbZH+lvFpOacuyoeXfSSyWvuTu3lwrlp0c5P4qkpgrxW/i1chFRQTqPutpeuSwt8IiOyc31e4M5jyy2JdQMQdAKiNpGccxTmfD5cVwpi8dM4IsSP2fp0v16Wan7vAiCb5FsMHg0NATwLyxPGdujf6+FG+SG3xzu5WsDcDjUfcg7kX5t7AsaN2FIzBvJJaJjzu/eEa0mRycNG4GFrd0iil2c/aWq1H+MjELb3d98fRwaUBMnxHfzPKJILsjopfvHE0MjGROi0dC2St8oKxWN1w87M8hzaS4S45qoU0YNN+O3eSZoCb7mwRQ1WuboU7l3qjgajc5Lhb5ZfiAiD1CHj0f3BEA1W9VGtPO+3WPz2rsw8bDXckyDu0aq42UEQMnFHV+f1EgnfAPaQfI5pI1reP5dX8QwmToB1kyHejSohtUJU7E32I+lEDYP5mNG/pa6HdSJUQGtI4LOHxPIsoMbMUkNo7Q2Zk0Bwh3l9M+MsOrq4FdvzixBmRXVpmO14IkmLiisN2DTB5vfHUkYP94OYF84GHrnvM4n0ebRF+RqBg3RuHfun7uOddGh+q+o+ZW3EYaPdWQ35uinrqSlUoyKO4FN1sL8VLolW3hZ83TI+eGiMTeAso2KC9iJTpDawU=
  on:
    tags: true
    repo: Heretik-Corp/ngx-objectmanager
