sudo: required
addons:
  chrome: stable
language: node_js
node_js:
- node
script:
- npm run test-ci
- npm run build-ci
before_deploy:
- cd dist/ngxobjectmanager
deploy:
  provider: npm
  email: smiles2424@gmail.com
  skip_cleanup: true
  api_key:
    secure: 8ASFhshMdY5h9WOy/RzYZaAxAIi3TlXOtD1pdNgH7m42VTCU6ipQydFpd7mIdq9OVRViO4lEW0hjMl8xBMwAB4VPnCFMaZWBDLhGaZJrF9Ey+SXSNMj3EpqcukBxaTd63Ic8IEUWs+n5KIfeiOvghIL/zgMEyvXewHp6wzTkDKy3PNmpmercxD6ShOn35t2IPi+oVM/hEN70DQOrjic+x+wiPs7qsTK03AWWgO6xCzbIa2w0yYKRH/bDI8KIklT2nGdAGkwvmURsDStr13JpVtPjWecgHCPzFiuisQam2lihQMkzoITQYXZGHPSnot+A5L8sJXo2AI/AkFmKt+x5AUKSTO5Fs6MaxAPG2HGHq0fzEkDN2WRE2E3W+nE7jprqtiKwZNRlA3FIca7kslaADKvC+SEkB/3M2eoNvKk8z8jYg06f4ym78u1OEOiOXCRmXlvvd6xWF+NqY876bdASAGYlrVh6FR1QmF8PGalkhdiZAY5b6jZB3MziVOIA08Xxs3asfOkRuufS6r9M2oZ4d7ZLBXDlkJQS4jW3XtuJcOXHfDjQv8VqkYcMqZ+t4xPeSCYOEVUK0WjSReW29jpuwb/nsgtZZcfVtNUHNTWmwKdHuc7YnxdSkrgOLamZKKWAk2OgYGq0x2K2Z8hTqiZMoT54uU/Y2MovdbrQ4krl0a4=
  on:
    tags: true
    repo: Heretik-Corp/ngx-objectmanager
